services:
  openttd:
    image: openttd
    build: .
    volumes:
    - ./data:/data
    environment:
    - openttd_branch=13.4
    ports:
    - 3979:3979/tcp
    - 3979:3979/udp
    - 3977:3977/tcp
    - 3977:3977/udp
    restart: always
